services:
  postgres:
    image: postgres:17
    container_name: ecomonitor-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: ecomonitor
      POSTGRES_USER: ecomonitor_user
      POSTGRES_PASSWORD: meteo

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
