services:

  postgres:
    image: postgres:17

    container_name: ecomonitor-db

    environment:
      POSTGRES_DB: ecomonitor
      POSTGRES_USER: ecomonitor_user
      POSTGRES_PASSWORD: meteo

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./EcoMonitor.Api

    container_name: ecomonitor-api

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ecomonitor;Username=ecomonitor_user;Password=meteo"

    ports:
      - "8080:8080"

    depends_on:
      - postgres
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: ecomonitor_pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: tutunberg@eco.com
      PGADMIN_DEFAULT_PASSWORD: meteo
      PGADMIN_CONFIG_SERVER_MODEL: "False"

    ports:
      - "1488:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass

    depends_on:
      - postgres


volumes:
  postgres_data:
  pgadmin_data:
